name: CI Pipeline
run-name: ðŸ§ª CI Pipeline Containerized - ${{ github.event.head_commit.message }}


on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    services:
      meilisearch:
        image: getmeili/meilisearch:latest
        ports:
          - 7700:7700
        env:
          MEILI_ENV: development
    
    env:
      MEILISEARCH_URL: http://localhost:7700
      MEILISEARCH_KEY: ''
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: ctype, iconv, intl, pdo_sqlite
        coverage: pcov

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Wait for Meilisearch
      run: |
        for i in {1..30}; do
          curl -s http://localhost:7700/health && break
          echo "Waiting for Meilisearch..."
          sleep 1
        done

    - name: Prepare Data
      run: |
        mkdir -p data
        php bin/console app:update-data

    - name: Install Chrome Driver
      run: vendor/bin/bdi driver:chromedriver drivers/

    - name: Check Code Style
      run: vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Execute Tests (PHPUnit)
      env:
        PANTHER_NO_HEADLESS: 0
        PANTHER_CHROME_DRIVER_BINARY: ./drivers/chromedriver
      run: php bin/phpunit --coverage-text